export interface RecommendationModel{
    id: string,
    ticker: string,
    targetTo: number,
    targetFrom: number,
    company: string,
    action: string,
    brokerage: string,
    ratingFrom: string,
    ratingTo: string,
    time: string,
    recommendationScore: number,
    avrgSentiment: number,
    percentageIncrease: number,
}