services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: stocks
      POSTGRES_USER: stocks
      POSTGRES_DB: stocks
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080