name: Frontend CI/CD

on:
  push:
    paths:
      - 'stocks-frontend/**'
      - '.github/workflows/frontend.yml'
    branches:
      - main

env:
  AWS_REGION: us-east-1
  S3_BUCKET_NAME: stocks-frontend-bucket 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: stocks-frontend
        run: npm ci

      - name: Inject backend URL into .env
        working-directory: stocks-frontend
        run: echo "VITE_BACKEND_URL=${{ secrets.BACKEND_URL }}" > .env


      - name: Build Vue app
        working-directory: stocks-frontend
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync to S3 bucket
        run: |
          aws s3 sync ./stocks-frontend/dist s3://${{ env.S3_BUCKET_NAME }} --delete --acl public-read
